# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				arrow = true
				cow = true
				pig = true
				skeleton = true
				bat = true
				frog = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				wandering_trader = true
				wither_skeleton = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				minecart = true
				leash_knot = true
				mooshroom = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				tropical_fish = true
				chest_minecart = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				blaze = true
				endermite = true
				cat = true
				zombie = true
				sheep = true
				player = true
				pufferfish = true
				wolf = true
				villager = true
				zombie_villager = true
				tnt_minecart = true
				boat = true
				painting = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.tconstruct]
				sky_slime = true

			[light_sources.settings.entities.blue_skies]
				crystal_camel = true
				infested_swarmer = true
				reindeer = true
				venom_spider = true
				armored_frost_spirit = true
				whistleshell_crab = true
				municipal_monkfish = true
				jelly_drifter = true
				crogre = true
				sliv = true
				stardust_ram = true
				shade_monitor = true
				nyctofly = true
				horizofin_tunid = true
				seclam = true
				cosmic_fox = true
				charscale_moki = true
				emberback = true
				grittle_flatfish = true

			[light_sources.settings.entities.youkaishomecoming]
				lamprey = true
				rumia = true

			[light_sources.settings.entities.alexsmobs]
				crocodile = true
				kangaroo = true
				hammerhead_shark = true
				murmur_head = true
				blue_jay = true
				emu = true
				mimic_octopus = true
				triops = true
				gazelle = true
				catfish = true
				tasmanian_devil = true
				centipede_tail = true
				cosmic_cod = true
				underminer = true
				skunk = true
				roadrunner = true
				terrapin = true
				rattlesnake = true
				gorilla = true
				flying_fish = true
				leafcutter_ant = true
				capuchin_monkey = true
				cockroach = true
				murmur = true
				lobster = true
				grizzly_bear = true
				centipede_body = true
				rocky_roller = true
				centipede_head = true
				mantis_shrimp = true
				raccoon = true
				flutter = true
				fly = true
				hummingbird = true
				crow = true
				banana_slug = true
				elephant = true
				bison = true
				sugar_glider = true

			[light_sources.settings.entities.biomemakeover]
				decayed = true
				dragonfly = true
				moth = true

			[light_sources.settings.entities.aether]
				cockatrice = true
				slider = true
				golden_swet = true
				evil_whirlwind = true
				blue_swet = true
				zephyr = true
				flying_cow = true
				whirlwind = true
				valkyrie = true
				phyg = true
				aerbunny = true
				lightning_knife = true
				sheepuff = true
				aerwhale = true
				aechor_plant = true
				mimic = true
				moa = true
				sentry = true
				valkyrie_queen = true

			[light_sources.settings.entities.hamsters]
				hamster = true

			[light_sources.settings.entities.vanillabackport]
				happy_ghast = true

			[light_sources.settings.entities.naturalist]
				deer = true
				zebra = true
				snail = true
				canary = true
				firefly = true
				bluejay = true
				snake = true
				cardinal = true
				catfish = true
				robin = true
				dragonfly = true
				boar = true
				bass = true
				tortoise = true
				butterfly = true
				giraffe = true
				bear = true
				sparrow = true
				lizard = true
				finch = true

			[light_sources.settings.entities.atmospheric]
				tetra = true

			[light_sources.settings.entities.betternether]
				firefly = true
				hydrogen_jellyfish = true

			[light_sources.settings.entities.immersive_aircraft]
				gyrodyne = true
				quadrocopter = true

			[light_sources.settings.entities.upgrade_aquatic]
				perch = true
				nautilus = true

			[light_sources.settings.entities.ribbits]
				ribbit = true

			[light_sources.settings.entities.touhou_little_maid]
				power_point = true
				maid = true
				fairy = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				stationary_contraption = true
				package = true
				contraption = true

			[light_sources.settings.entities.quark]
				shiba = true
				totem = true
				forgotten = true
				toretoise = true
				glass_frame = true
				foxhound = true
				stoneling = true
				pickarang = true
				flamerang = true

			[light_sources.settings.entities.ecologics]
				coconut_crab = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.irons_spellbooks]
				dead_king_corpse = true
				pyromancer = true
				necromancer = true

			[light_sources.settings.entities.environmental]
				deer = true
				reindeer = true

			[light_sources.settings.entities.mysticsbiomes]
				butterfly = true

			[light_sources.settings.entities.twilightforest]
				deer = true
				ice_arrow = true
				tiny_bird = true
				giant_miner = true

			[light_sources.settings.entities.create_enchantment_industry]
				hyper_experience_bottle = true
				hyper_experience_orb = true

			[light_sources.settings.entities.domesticationinnovation]
				psychic_wall = true

			[light_sources.settings.entities.neapolitan]
				chimpanzee = true
				banana_peel = true

